markdown: kramdown
sass:
  style: :compressed
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
exclude:
  - bin
  - vendor
  - LICENSE.txt
  - README.md
  - TODO
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
twitter:
  username: sorentwo
title: Soren Blog
description: "Writings on web stability, performance and growth"
defaults:
  -
    values:
      layout: default
      theme: light
